### ISSUE TITLE
'pos_embed'

### ISSUE THREAD

**Issue by YDxiaoran** [heshuting555/TransReID#10]
when run train.py,i have this question,thanks!!!

**Comment by heshuting555** [comment]
Can you describe your problem in detail?
I cannot understand your question.

**Comment by YDxiaoran** [comment]
thank you for your reply ,actually i don't know how to set the parameter of "_C.MODEL.PRETRAIN_PATH”，when I try some value,the running result is 'pos_embed'

**Comment by heshuting555** [comment]
You need to download the ImageNet pretrained transformer model : vit or deit. 
and write its path to `MODEL.PRETRAIN_PATH` .

**Comment by YDxiaoran** [comment]
I do downloaded the mode:vit ,then I set it to "...../vit_small_p16_224-15ec54c9.pth' and run the train.py ,the result is :"pos_embed,when i try to use "python train.py --config_file configs/Market/vit_transreid_stride.yml MODEL.DEVICE_ID "('0')"" in Terminal, it stays in the state of   "transreid.train INFO: start training"  all the time.

**Comment by heshuting555** [comment]
Yes, using command: 
python train.py --config_file configs/Market/vit_transreid_stride.yml

Can you share me your train_log.txt ?

**Comment by YDxiaoran** [comment]
好的
D:\anaconda\envs\pytorch\python.exe E:/re-id/TransReID-main/train.py
2021-05-21 09:42:37,467 transreid INFO: Saving model in the path :E:\re-id\TransReID-main\log
2021-05-21 09:42:37,467 transreid INFO: Namespace(config_file='', local_rank=0, opts=[])
2021-05-21 09:42:37,467 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 16
  NUM_WORKERS: 0
  SAMPLER: softmax
DATASETS:
  NAMES: market1501
  ROOT_DIR: E:\re-id\market1501
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [384, 128]
  SIZE_TRAIN: [384, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: False
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: on
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: triplet
  NAME: resnet50
  NECK: bnneck
  NO_MARGIN: False
  PRETRAIN_CHOICE: imagenet
  PRETRAIN_PATH: model/backbones/backbone/vit_small_p16_224-15ec54c9.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: None
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: E:\re-id\TransReID-main\log
SOLVER:
  BASE_LR: 0.0003
  BIAS_LR_FACTOR: 1
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 10
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 10
  GAMMA: 0.1
  IMS_PER_BATCH: 2
  LARGE_FC_LR: False
  LOG_PERIOD: 100
  MARGIN: 0.3
  MAX_EPOCHS: 50
  MOMENTUM: 0.9
  OPTIMIZER_NAME: Adam
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: False
  FEAT_NORM: yes
  IMS_PER_BATCH: 2
  NECK_FEAT: after
  RE_RANKING: False
  WEIGHT: 
=> Market1501 loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gallery  |   751 |    15913 |         6
  ----------------------------------------
using softmax sampler
using resnet50 as a backbone
Traceback (most recent call last):
  File "E:/re-id/TransReID-main/train.py", line 68, in <module>
    model = make_model(cfg, num_class=num_classes, camera_num=camera_num, view_num = view_num)
  File "E:\re-id\TransReID-main\model\make_model.py", line 402, in make_model
    model = Backbone(num_class, cfg)
  File "E:\re-id\TransReID-main\model\make_model.py", line 71, in __init__
    self.base.load_param(model_path)
  File "E:\re-id\TransReID-main\model\backbones\resnet.py", line 132, in load_param
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'pos_embed'

**Comment by YDxiaoran** [comment]
好的，麻烦了
[train_log.txt](https://github.com/heshuting555/TransReID/files/6519539/train_log.txt)

**Comment by heshuting555** [comment]
Sorry for my late reply.

Have you solved the problem?

I recommend that you can use the default settings that provided.
