### ISSUE TITLE
camid一定要int吗

### ISSUE THREAD

**Issue by guanyonglai** [heshuting555/TransReID#12]
我看camid也参与了网络的计算，请问下camid具体参与什么计算呢，一般不是测试的时候才会用到camid吗？

**Comment by michuanhaohao** [comment]
camid是相机标签，用于SIE模块对相机进行编码用的，必须是INT型。如果你只想跑baseline的话，训练的时候可以不用输入camid，稍微改一下代码，把cam相关的去掉就行。
