### ISSUE TITLE
请问您在V2版本论文中的Visualization of the learned attention masks是怎么做的

### ISSUE THREAD

**Issue by July-zh** [heshuting555/TransReID#13]

**Comment by heshuting555** [comment]
We refer to the following code base for the visualization code in the paper.
https://github.com/jacobgil/vit-explain
https://github.com/jeonsworld/ViT-pytorch/blob/main/visualize_attention_map.ipynb

Hope the answer is helpful.

**Comment by July-zh** [comment]
Thanks!
