### ISSUE TITLE
base.sie_embed

### ISSUE THREAD

**Issue by znothingisimpossible** [heshuting555/TransReID#14]
Hello, I have a problem now. This problem is that when I use the trained model to test, a keyError:'base.sie_embed' appears. Where should I start to solve this? I look forward to your reply.

**Comment by heshuting555** [comment]
Maybe the config what's your test and train is not the same file?

Is it solve? 

If it doesn't work, you can share me the command what's you using testing or training.

**Comment by znothingisimpossible** [comment]
The problem has been solved, thank you

**Comment by heshuting555** [comment]
You are welcome!

**Comment by tesorrells** [comment]
How was this solved @znothingisimpossible ?

**Comment by ledinhtri97** [comment]
@znothingisimpossible Hello, how did you solve this? thank you
