### ISSUE TITLE
Test method for vehicleid dataset

### ISSUE THREAD

**Issue by lhc11171552** [heshuting555/TransReID#15]
Since the vehicleid dataset is different from other datasets, an error will be reported if the vehicleid dataset is tested according to the test method of other datasets.

**Comment by heshuting555** [comment]
you can follow the command in the README like that:
`python test.py --config_file configs/VehicleID/vit_transreid_stride.yml MODEL.DEVICE_ID "('0')" TEST.WEIGHT '../logs/vehicleID_vit_transreid_stride/transformer_120.pth'`

**Comment by lhc11171552** [comment]
Still an error:Traceback (most recent call last):
  File "test.py", line 68, in <module>
    num_query)
  File "/home/w/lhc/TransReID-main_vehicleid/processor/processor.py", line 166, in do_inference
    cmc, mAP, _, _, _, _, _ = evaluator.compute()
  File "/home/w/lhc/TransReID-main_vehicleid/utils/metrics.py", line 131, in compute
    cmc, mAP = eval_func(distmat, q_pids, g_pids, q_camids, g_camids)
  File "/home/w/lhc/TransReID-main_vehicleid/utils/metrics.py", line 81, in eval_func
    assert num_valid_q > 0, "Error: all query identities do not appear in gallery"
AssertionError: Error: all query identities do not appear in gallery

**Comment by heshuting555** [comment]
You can print your `distmat.shape` to check the error!

Hope the answer is helpful!

**Comment by 459737087** [comment]
Hello !! Did you find the reason?
I also met this.
