### ISSUE TITLE
跨域测性能好吗？

### ISSUE THREAD

**Issue by justopit** [heshuting555/TransReID#16]
跨域测性能好吗？做了一次伸手党。。模型下载速度有点慢，想问一问

**Comment by heshuting555** [comment]
这个没有试过呢，应该不错的吧~

**Comment by michuanhaohao** [comment]
> 跨域测性能好吗？做了一次伸手党。。模型下载速度有点慢，想问一问

比R50好一些，但也没有特别好了，学术数据集太小了，直接跨域都不太行
