### ISSUE TITLE
如何获取market的label分类

### ISSUE THREAD

**Issue by cxiang0403** [heshuting555/TransReID#17]
我使用market数据集训练好模型之后，可以获取pid的得分，请问如何对应到market的各个label中呢？

**Comment by michuanhaohao** [comment]
测试阶段pid写在image文件名里面，可以直接对应。训练阶段对于pid做了一个relabel，你可以在market.py里面把这个映射的dictionary存下来

**Comment by cxiang0403** [comment]
谢谢，只需要存下pid到label的映射吗？在损失值传递的时候不需要改损失函数吗

**Comment by cxiang0403** [comment]
谢谢，只需要存下pid到label的映射吗？在损失值传递的时候不需要改损失函数吗

**Comment by michuanhaohao** [comment]
> 谢谢，只需要存下pid到label的映射吗？在损失值传递的时候不需要改损失函数吗

没太懂你的意思，softmax分类得分的第一维就是0号ID，第二维就是1号ID，后面要做什么就根据自己的需求来就行

**Comment by cxiang0403** [comment]
> > 谢谢，只需要存下pid到label的映射吗？在损失值传递的时候不需要改损失函数吗
> 
> 没太懂你的意思，softmax分类得分的第一维就是0号ID，第二维就是1号ID，后面要做什么就根据自己的需求来就行

好的，我先尝试下。再次表示感谢
