### ISSUE TITLE
Is the test method of the Veri dataset the same as the test method of the Vehicleid dataset?

### ISSUE THREAD

**Issue by lhc11171552** [heshuting555/TransReID#18]

**Comment by lhc11171552** [comment]
Have you modified some of the parameters

**Comment by heshuting555** [comment]
You can refer to the README
The only difference is that We test 10 times and get the final average score to avoid randomness.
The command like that:
python test.py --config_file configs/VehicleID/vit_transreid_stride.yml MODEL.DEVICE_ID "('0')" TEST.WEIGHT '../logs/vehicleID_vit_transreid_stride/transformer_120.pth'

**Comment by lhc11171552** [comment]
Thanks a lot

**Comment by heshuting555** [comment]
You are welcome~~~
