### ISSUE TITLE
 CUDA out of memory.

### ISSUE THREAD

**Issue by yuguangxie** [heshuting555/TransReID#2]
推荐的显存大小是16GB，请问显存小的时候有其他办法可以训练或评估吗？

**Comment by michuanhaohao** [comment]
> 推荐的显存大小是16GB，请问显存小的时候有其他办法可以训练或评估吗？

（1）减小batch size，性能会差一两个点
（2）选择ViT-small的backbone做实验也可以，稍微修改一下代码

**Comment by heshuting555** [comment]
可以跑`vit_transreid.yml` 系列只占用7G+显寸，感谢关注。

**Comment by yuguangxie** [comment]
感谢，可以训练
