### ISSUE TITLE
should cam index in the testset correspond to the training set?

### ISSUE THREAD

**Issue by sophieyl** [heshuting555/TransReID#20]
for example, I only get cam 1,2,3,4 while training and I enable the cam sie module.
Howerer, in the testset, I get 1,2,3,4,5，what should I do with the cam 5 since it was not been trained ?

**Comment by heshuting555** [comment]
Hello, good question.
In the current version, we haven't solved this issue. In the future, we may tackle this problem.
Thank you for your attention!
