### ISSUE TITLE
关于混合模型

### ISSUE THREAD

**Issue by Wang-pengfei** [heshuting555/TransReID#21]
请问一下怎么设置可以跑CNN+几层transformer的结构呢？我看代码里面是有这个HybridEmbed模型的

**Comment by heshuting555** [comment]
把backbone换成HybridEmbed类型的就可以呢，但现有的代码还没有设置。

**Comment by Wang-pengfei** [comment]
好的，那我去做一下， 我看到代码里面有这个模型，我还以为可以直接跑起来。
