### ISSUE TITLE
MSMT17数据集中list文件内容命名的含义是什么

### ISSUE THREAD

**Issue by July-zh** [heshuting555/TransReID#3]
eg:
0000/0000_045_12_0303morning_0006_2.jpg 0
0000/0000_046_12_0303morning_0006_2_ex.jpg 0

**Comment by heshuting555** [comment]
eg:
0000/0000_045_12_0303morning_0006_2.jpg 0
0 代表人的类别——pid；
12 代表camera的类别——camid；
其余的命名信息可以参考论文 [MSMT17](https://arxiv.org/pdf/1711.08565.pdf) 或者询问论文作者。

感谢关注～

**Comment by July-zh** [comment]
好的 谢谢
