### ISSUE TITLE
所有的数据集都是拿测试集当的验证集？

### ISSUE THREAD

**Issue by July-zh** [heshuting555/TransReID#4]

**Comment by heshuting555** [comment]
Hi～
为了方便得到实验结果，实验配置是训练完成120个epoch之后测试，
测试得到最终的report 测试集结果，没有分验证集的这种感觉呢。

**Comment by heshuting555** [comment]
Hi～
学术界就一直默认这么用呢，
理论上没有验证集，模型训练完毕后直接在测试集上测试准确度。
只不过命名为val_loader。
