### ISSUE TITLE
Training on external dataset without query images

### ISSUE THREAD

**Issue by Jack6680** [heshuting555/TransReID#5]
Good afternoon! 
Will you provide the code for training on external datasets? There are a lot of tasks, where datasets provided in format

```
 <folder1 "class name1"> : [img11,img21,...],
 <folder2 "class name2"> : [img21,img22,...],
```

It would be nice to test this approach on other datasets.
Thank you!

**Comment by heshuting555** [comment]
Hi, Jack6680

The unified data set format in the code is：

dataset.append((img_path, pid, camid, viewid)) If you don't have camid and viewid, you can use number 1 instead. 

Hope the answer can help you~ Thanks~
